---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-registry-operator-dev-v1alpha1-registry
  failurePolicy: Fail
  name: mregistry-v1alpha1.kb.io
  rules:
  - apiGroups:
    - registry-operator.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registries
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-registry-operator-dev-v1alpha1-registry
  failurePolicy: Fail
  name: vregistry-v1alpha1.kb.io
  rules:
  - apiGroups:
    - registry-operator.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registries
  sideEffects: None
