apiVersion: registry-operator.dev/v1alpha1
kind: Registry
metadata:
  labels:
    app.kubernetes.io/name: registry-operator
    app.kubernetes.io/managed-by: kustomize
  name: registry-sample
spec: {}
