apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "registry-operator.fullname" . }}-manager-role
  labels:
    {{- include "registry-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry-operator.dev
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registry-operator.dev
  resources:
  - registries/finalizers
  verbs:
  - update
- apiGroups:
  - registry-operator.dev
  resources:
  - registries/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "registry-operator.fullname" . }}-manager-rolebinding
  labels:
    {{- include "registry-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "registry-operator.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "registry-operator.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'
