{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "registry-operator.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "registry-operator.fullname" . }}-serving-cert
  labels:
    {{- include "registry-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: '{{ include "registry-operator.fullname" . }}-webhook-service'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate-registry-operator-dev-v1alpha1-registry
  failurePolicy: Fail
  name: {{ include "registry-operator.fullname" . }}-mutating-webhook
  rules:
  - apiGroups:
    - registry-operator.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registries
  sideEffects: None
{{- end }}
