apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "registry-operator.fullname" . }}-controller-manager
  labels:
    {{- include "registry-operator.labels" . | nindent 4 }}
  {{- with .Values.controllerManager.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
